version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo Packaging templates...
      - aws s3 cp lambdafunc.yaml s3://iac-bucket-azamcloud/
      - aws s3 cp s3-event.yaml s3://iac-bucket-azamcloud/
      - aws cloudformation deploy --template-file master-event.yaml --stack-name ecs-infra-stack --capabilities CAPABILITY_NAMED_IAM --parameter-overrides file://prod-params.json

artifacts:
  files:
    - '**/*'
