AWSTemplateFormatVersion: '2010-09-09'
Description: Master stack for Image Processor (S3 + Lambda + Events)
Parameters:
  InputBucketName:
    Type: String

  OutputBucketName:  
    Type: String

  FunctionName:
    Type: String  

  GitHubOwner:
    Type: String
    
  GitHubRepo:
    Type: String
    
  GitHubToken:
    Type: String
    NoEcho: true

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/s3-event.yaml
      Parameters:
        InputBucketName: !Ref InputBucketName
        OutputBucketName: !Ref OutputBucketName
        LambdaArn: !GetAtt LambdaStack.Outputs.Lambda

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/lambdafunc.yaml
      Parameters:
        FunctionName: !Ref FunctionName
        InputBucket: !GetAtt S3Stack.Outputs.InputBucket
        OutputBucket: !GetAtt S3Stack.Outputs.OutputBucket

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/codepipeline.yaml
      Parameters:
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubToken: !Ref GitHubToken
        Lambda: !GetAtt LambdaStack.Outputs.Lambda
        


