AWSTemplateFormatVersion: '2010-09-09'
Description: S3 resources for event-driven image processor

Parameters:
  InputBucketName:
    Type: String
  Lambda:
    Type: String

Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !Ref Lambda

Outputs:
  InputBucket:
    Value: !GetAtt InputBucket.Arn





